apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: node-server
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31000