version: "3" ## especifica a versão do docker-compose file

services:
  app: ## nome do serviço
    build: .
    working_dir: /usr/app
    command: npm run prod ## comando a executar
    restart: always
    environment:
      - PORT=3001
    ports:
      - 3001:3001 ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    volumes:
      - .:/usr/app
    # networks:
    #   backend:
    #     ipv4_address: 172.30.0.2
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.5'
        reservations:
          memory: 512M

  web:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    depends_on:
      - app


# networks: 
#   backend:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.30.0.0/16

# volumes:
#   db-data:
#     external: true